language: c
sudo: false # only for faster builds
script:
  - clang -coverage -O0 keerthi.c -o keerthi
  - ./keerthi
  - gcov keerthi.c
  - clang -coverage -O0 demon.c -o demon
  - ./demon
  - gcov demon.c
  - clang -coverage -O0 jaya.c -o jaya
  - ./jaya
  - gcov jaya.c
after_success:
  - bash <(curl -s https://codecov.io/bash)

